"""update all tables

Revision ID: 2a0ea2b61229
Revises: cb8064bb5d82
Create Date: 2025-09-29 17:53:43.671591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a0ea2b61229'
down_revision: Union[str, Sequence[str], None] = 'cb8064bb5d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users')
    # op.drop_table('subscriptions')
    # op.drop_table('transcripts')
    # op.drop_table('memos')
    # op.drop_table('recording_sessions')
    # op.drop_table('boards')
    # op.drop_table('notifications')
    # op.drop_table('folders')
    # op.drop_table('summaries')
    # op.drop_table('audio_data')
    # op.drop_table('recording_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_results',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('recording_results_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('recording_session_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('speaker_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recording_session_id'], ['recording_sessions.id'], name='recording_results_recording_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recording_results_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('audio_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('audio_data_board_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audio_data_pkey'))
    )
    op.create_table('summaries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('summary_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('summaries_board_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('summaries_transcript_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('summaries_pkey'))
    )
    op.create_table('folders',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('folders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name='folders_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='folders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('boards',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('boards_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invite_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invite_role', sa.VARCHAR(), server_default=sa.text("'editor'::character varying"), autoincrement=False, nullable=True),
    sa.Column('invite_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name='boards_folder_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='boards_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='boards_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('recording_sessions',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('recording_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('recording', 'stopped', 'saved', name='recording_type'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name='recording_sessions_board_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='recording_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recording_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('memos',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('memos_board_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('memos_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('memos_pkey'))
    )
    op.create_table('transcripts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('speaker_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('transcripts_board_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['recording_results.id'], name=op.f('transcripts_result_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transcripts_pkey'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('plan', postgresql.ENUM('free', 'pro', 'enterprise', name='plan_type'), server_default=sa.text("'free'::plan_type"), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('payment_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('picture', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('oauth_provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('oauth_sub', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
