"""fix end_date nullable

Revision ID: a00be96e64d7
Revises: 2a0ea2b61229
Create Date: 2025-09-29 18:00:12.087154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a00be96e64d7'
down_revision: Union[str, Sequence[str], None] = '2a0ea2b61229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
recording_type = sa.Enum('recording', 'stopped', 'saved', name='recordingtype')
plan_type = sa.Enum("free", "pro", "enterprise", name="plantype")
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. enum 타입 생성
    plan_type.create(op.get_bind(), checkfirst=True)
    recording_type.create(op.get_bind(), checkfirst=True)

    # 2. subscriptions.plan → enum으로 변경 (기본값 처리)
    op.execute("ALTER TABLE subscriptions ALTER COLUMN plan DROP DEFAULT")
    op.execute("""
               ALTER TABLE subscriptions
               ALTER
               COLUMN plan TYPE plantype
            USING plan::text::plantype
               """)
    op.execute("ALTER TABLE subscriptions ALTER COLUMN plan SET DEFAULT 'free'")

    # 3. recording_sessions.status → enum으로 변경
    op.execute("""
               ALTER TABLE recording_sessions
               ALTER
               COLUMN status TYPE recordingtype
            USING status::text::recordingtype
               """)

    # ✅ end_date, period_end nullable 허용
    op.create_table('recoding_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('allocated_minutes', sa.Integer(), nullable=True),
    sa.Column('used_minutes', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audio_data', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audio_data', 'board_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('boards', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('boards_id_seq'::regclass)"))
    op.alter_column('boards', 'folder_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('boards', 'owner_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('folders', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('folders_id_seq'::regclass)"))
    op.alter_column('folders', 'parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('memos', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('memos', 'board_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('memos', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notifications', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('recording_results', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('recording_results_id_seq'::regclass)"))
    op.alter_column('recording_results', 'recording_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('recording_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('recording_sessions_id_seq'::regclass)"))
    op.alter_column('recording_sessions', 'board_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('recording_sessions', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('recording_sessions', 'status',
               existing_type=postgresql.ENUM('recording', 'stopped', 'saved', name='recording_type'),
               type_=sa.Enum('recording', 'stopped', 'saved', name='recordingtype'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=postgresql.ENUM('free', 'pro', 'enterprise', name='plan_type'),
               type_=sa.Enum('free', 'pro', 'enterprise', name='plantype'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::plan_type"))
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscriptions', 'payment_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('summaries', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('summaries', 'transcript_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('summaries', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transcripts', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transcripts', 'result_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('transcripts', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
               ALTER TABLE recording_sessions
               ALTER
               COLUMN status TYPE text
           USING status::text
               """)

    # 2. subscriptions.plan → text로 되돌리기
    op.execute("ALTER TABLE subscriptions ALTER COLUMN plan DROP DEFAULT")
    op.execute("""
               ALTER TABLE subscriptions
               ALTER
               COLUMN plan TYPE text
           USING plan::text
               """)
    op.execute("ALTER TABLE subscriptions ALTER COLUMN plan SET DEFAULT 'free'")

    # 3. enum 타입 삭제
    recording_type.drop(op.get_bind(), checkfirst=True)
    plan_type.drop(op.get_bind(), checkfirst=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('transcripts', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transcripts', 'result_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('transcripts', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('summaries', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('summaries', 'transcript_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('summaries', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'payment_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.Enum('free', 'pro', 'enterprise', name='plantype'),
               type_=postgresql.ENUM('free', 'pro', 'enterprise', name='plan_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::plan_type"))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recording_sessions', 'status',
               existing_type=sa.Enum('recording', 'stopped', 'saved', name='recordingtype'),
               type_=postgresql.ENUM('recording', 'stopped', 'saved', name='recording_type'),
               existing_nullable=False)
    op.alter_column('recording_sessions', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('recording_sessions', 'board_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('recording_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('recording_sessions_id_seq'::regclass)"))
    op.alter_column('recording_results', 'recording_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('recording_results', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('recording_results_id_seq'::regclass)"))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('memos', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('memos', 'board_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('memos', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('folders', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('folders', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('folders_id_seq'::regclass)"))
    op.alter_column('boards', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('boards', 'folder_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('boards', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('boards_id_seq'::regclass)"))
    op.alter_column('audio_data', 'board_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('audio_data', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('recoding_usage')
    # ### end Alembic commands ###
