"""add user_id to folders

Revision ID: 74c2857792b7
Revises: a00be96e64d7
Create Date: 2025-10-01 16:17:55.115115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c2857792b7'
down_revision: Union[str, Sequence[str], None] = 'a00be96e64d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('workspace_name', sa.String(), nullable=True),
    sa.Column('owner_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_auth_user_id'), 'notion_auth', ['user_id'], unique=True)
    op.add_column('folders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'user_id')
    op.drop_index(op.f('ix_notion_auth_user_id'), table_name='notion_auth')
    op.drop_table('notion_auth')
    # ### end Alembic commands ###
